user_blog/config/routes.rb
Rails.application.routes.draw do
  devise_for(:users)
  root("articles#index")

  resources(:articles) do
    resources(:comments)
    member do
      post("increase_report_count")
    end
  end
end

user_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

user_blog/app/models/article.rb
class Article < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 10}

  before_update do
    puts "check for report count"
    if self.report_count >= 3
      self.status = "archived"
    end
  end
end

user_blog/app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

user_blog/app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ["public", "private", "archived"]

  included do
    validates :status, inclusion: {in: VALID_STATUSES}
  end

  class_methods do
    def public_count
      where(status: "public").count
    end
  end

  def archived?
    status == "archived"
  end
end

user_blog/app/models/user.rb
class User < ApplicationRecord
  has_many :article
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise(
    :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable
  )
end

user_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

user_blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if can?(:create, @article) and @article.save
      redirect_to(@article)
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if can?(:update, @article) and @article.update(article_params)
      redirect_to(@article)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if can?(:destroy, @article)
      @article.destroy
    end

    redirect_to(root_path, status: :see_other)
  end

  def increase_report_count
    @article = Article.find(params[:id])
    @article.increment!(:report_count)
    @article.save
    redirect_to(@article)
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status, :image, :user_id)
  end

end

user_blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to(article_path(@article))
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to(article_path(@article), status: :see_other)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

user_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

user_blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

user_blog/app/helpers/comments_helper.rb
module CommentsHelper
end

user_blog/app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
  </div>

  <div>
     <%= form.label :image %><br>
    <%= form.file_field :image %><br>
  </div>
  <%= form.hidden_field :user_id, value: current_user.id if current_user %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

user_blog/app/views/articles/edit.html.erb
<h1>Update Article</h1>

<%= render "form", article: @article %>

user_blog/app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>

  <%= link_to "New Article", new_article_path  %>
</ul>


<%= button_to "logout", destroy_user_session_path, method: :delete if current_user  %>
<%= link_to "login", new_user_session_path, method: :delete if !current_user  %>

user_blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

user_blog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body%></p><br />
<p>Report Count: <%= @article.report_count%></p><br />
<p>Status: <%= @article.status%></p><br />
<% if @article.image.attached? %>
  <%= image_tag @article.image %>
<% end %>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Delete", @article, data: {
    turbo_method: "delete",
    turbo_confirm: "Are You Sure?"
  } %></li>
  <%= link_to 'Report', increase_report_count_article_path(@article), data: {
    turbo_method: "post"
  }%>


</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

user_blog/app/views/comments/_comment.html.erb
<% unless comment.archived? %>
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>

user_blog/app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
  </div>

  <p>
    <%= form.submit %>
  </p>
<% end %>

user_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>